services:
  - type: web
    name: ether-userbot
    runtime: docker
    plan: free

    autoDeploy: false

    healthCheckPath: /

    envVars:
      - key: API_ID
        sync: false

      - key: API_HASH
        sync: false

      - key: OWNER_ID
        sync: false

      - key: BOT_TOKEN
        sync: false

      - key: MONGO_URI
        sync: false

      - key: PORT
        value: "10000"

      - key: WEB_SERVICE
        value: "true"
